json.id product.id
json.name product.name
json.price product.price
json.is_discounted? product.is_discounted?
json.tax product.tax
json.images product.images
json.description product.description
json.inventory product.inventory
json.supplier_id product.supplier_id
json.created_at product.created_at
json.updated_at product.updated_at