json.id product.id
json.name product.name
json.description product.description
json.price product.price
json.categories product.categories
json.images product.images
json.is_discounted? product.is_discounted?
json.tax product.tax
json.inventory product.inventory
json.supplier product.supplier
json.created_at product.created_at
json.updated_at product.updated_at